### ISSUE TITLE
New to Docker, a few questions

### ISSUE THREAD

**Issue by nshoes** [whoan/docker-build-with-cache-action#26]
Howdy! I have a few questions about this tool. I'm newer to Docker, so please bear with me and forgive me if I'm not clear or asking an obvious question.

- If I don't use a multi-stage build, are my images cached?
- If I have `push_image_and_stages: false`, are my images cached?
- If I have `push_image_and_stages: false` and no credentials for a registry, are my images cached?
- If I'm using images that I don't own on Docker Hub, I get this error:
```
The push refers to repository [docker.io/hexpm/elixir]
...
denied: requested access to the resource is denied
```
Do I have to have to be pulling images from repos that I own for my images to be cached?

Thank you in advance!

**Comment by whoan** [comment]
Hey @nshoes . These are my answers:

> * If I don't use a multi-stage build, are my images cached?

Yes

> * If I have `push_image_and_stages: false`, are my images cached?

No, because what we actually push, is the cache. It works pushing every stage and the final image as cache. Then, in further builds, it pulls every cached image (stages included) so docker recognize some steps already exist and and it does not run the steps again (ie: it uses the cached steps).

> * If I have `push_image_and_stages: false` and no credentials for a registry, are my images cached?

Did you mean `true` here? Anyway, your images won't be cached if they are not pushed, and you need credentials to push to a registry.

> (EDITED) * If I'm using images that I don't own on Docker Hub, I get an error (see above):

You don't need to own the repos to pull, unless they are private repos. It seems you are trying to create (and push) an image with the same name as another image in a repo you don't own. It's just a guess, I would need more context for this one.

**Comment by nshoes** [comment]
Awesome, thanks for clarifying!
