### ISSUE TITLE
Release Stability

### ISSUE THREAD

**Issue by jbarop** [whoan/docker-build-with-cache-action#31]
Hi,

our builds failed because of breaking changes in `docker-build-with-cache-action@v4`. I narrowed the version to `docker-build-with-cache-action@v4.3.0`. This worked fine yesterday, but today this release is gone.

As we require to have stable builds it would be nice, if there would be stable released versions.

**Comment by whoan** [comment]
Hi @jbarop . You are right, and I apologize for that. What I didn't see when I released v.4.30 is that I could break existent workflows which were using **v4** and the old method to login to AWS ECR.

I should have released v5 instead of v.4.3.0 from the beginning .

Please use **v5** instead of **v4.3.0** (which have the same changes), mainly if you want to use AWS ECR.
