### ISSUE TITLE
Feature : option to use build stage name instead of number for the tag of image stages

### ISSUE THREAD

**Issue by gaugau3000** [whoan/docker-build-with-cache-action#33]
Hi,

[User story like] :
As a developer
I would like to use intermediate images of multi-stage built during continuous integration using the stage name (e.g : _myimage_-stages:test instead of _myimage_-stages:3 if i need to use it later in ci)
So that i can add stages in my dockerfile without breaking ci.

[Gherkin]
Given my dockerfile used [named build](https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages) and I have set "tag_stage_image_by_label = true"
When it run the built of docker-build-with-cache-action
Then staging images should be named like _myimage_-stages:_stage_label_

Not sure of the feasibility.

Have a nice day.

**Comment by whoan** [comment]
I like the suggestion. I will take a look. Thanks @gaugau3000

**Comment by whoan** [comment]
I think a full implementation of this would need to have a mechanism to clean old stages in case you rename one, to avoid the stage to stay in the registry forever.

I am not sure now if I am going to merge the changes I have made so far to master. For the moment, you can use [name-stages branch](https://github.com/whoan/docker-build-with-cache-action/tree/name-stages).

**Comment by whoan** [comment]
As this change will create more versions of the *-stages images and due to GitHub's policy stated in #52 , I am going to hold off on this one. In addition, #51 made me think that you won't be able to use the *-stages images on further steps of the action; maybe I misunderstood the issue though.

I will close for the moment but If there are more people interested in this feature, feel free to open and continue discussion.

BTW, I won't remove [the branch](https://github.com/whoan/docker-build-with-cache-action/tree/name-stages) with the work for this feature in case someone needs it.
