### ISSUE TITLE
Clarification on cache location

### ISSUE THREAD

**Issue by quoimec** [whoan/docker-build-with-cache-action#57]
Hello! I've started using this action but I've been left slightly confused as to it's purpose and how it actually functions and was just wondering if you could clarify a few points for me please?

I'm mainly confused as to the cache location that is being used for the Docker images - is it using the Github repository cache? Or is it using the docker-stages images that get created when this action is run to cache the build stages? I'm using this on a fairly simple image where the bulk of the build time is from download of the initial FROM: statement. If the answer previous question is that the stages are cached in the Docker repository, I assume that means that I will not see any meaningful speed improvements from using this action?

Thank you!

**Comment by whoan** [comment]
Hi @quoimec . The cache is sent to the registry you configure in the action inputs, and you can choose GitHub like this:

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: hello-world

The cache are the tagged _*-stage_ images. If most of your build time is spent downloading the image set in the FROM statement, this action won't help as the purpose is to cache the build steps, so you download each step instead of building it again which is usually faster.

**Comment by quoimec** [comment]
Ah ok all good, looks like this actions is for a different use case then. For reference, this was the GH caching that I was talking about where data is cached in the git repo: https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows. Will have to use the GH action by the looks of it. Cheers anyway and thanks for the reply!
